// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcACWoWbp3lDZYYD_SdtXlevDADPTUbQw',
    appId: '1:231154984703:web:7e9a01601770bdd2cececa',
    messagingSenderId: '231154984703',
    projectId: 'haidenjem-db-1c9fd',
    authDomain: 'haidenjem-db-1c9fd.firebaseapp.com',
    storageBucket: 'haidenjem-db-1c9fd.appspot.com',
    measurementId: 'G-XB67FL1FHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlw3Rp9D4h6qx39CE0ogu9ExHkVj-76Uw',
    appId: '1:231154984703:android:c93a71f4d81c73eacececa',
    messagingSenderId: '231154984703',
    projectId: 'haidenjem-db-1c9fd',
    storageBucket: 'haidenjem-db-1c9fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrfHBYLLIev8tq5LFbeInrpbuyNt1m6Zk',
    appId: '1:231154984703:ios:dfcfb136c33bf0d2cececa',
    messagingSenderId: '231154984703',
    projectId: 'haidenjem-db-1c9fd',
    storageBucket: 'haidenjem-db-1c9fd.appspot.com',
    iosBundleId: 'com.example.haidenjem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrfHBYLLIev8tq5LFbeInrpbuyNt1m6Zk',
    appId: '1:231154984703:ios:c3400f31c1812003cececa',
    messagingSenderId: '231154984703',
    projectId: 'haidenjem-db-1c9fd',
    storageBucket: 'haidenjem-db-1c9fd.appspot.com',
    iosBundleId: 'com.example.haidenjem.RunnerTests',
  );
}
